# Generated by Django 5.1.5 on 2025-01-21 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_anonymous', models.IntegerField()),
                ('text', models.TextField()),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('url_before', models.URLField()),
                ('qr_width', models.IntegerField(default=300)),
                ('qr_height', models.IntegerField(default=300)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('answer_time', models.DateTimeField(auto_now_add=True)),
                ('live_time', models.DateTimeField(blank=True, null=True)),
                ('is_answered', models.IntegerField()),
                ('mail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='mailApp.mail')),
            ],
        ),
    ]
